### ISSUE TITLE
Automatically Prefix Color Codes for Quotes and Name Colors

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#120]
**Is your feature request related to a problem? Please describe.**
This happens a lot: someone comes on Info looking for help on settings/quote_color and /name_color because just inputting the color code doesn't work. Because they need to input it with { or |.

**Describe the solution you'd like**
The color code is ALWAYS gonna need to have either { or | on it. So why don't we make it so that the player doesn't need to input that part? Ideally the code should be able to check input to see if a player has already prefixed their color code with a { or | and, in those cases, do nothing. Otherwise it can just automatically add | or { (as you prefer) to the start of the entered code.

**Comment by TehomCD** [comment]
Is there any drawbacks with escaping all color codes in chat channels? We could set them all player input to be raw/escaped in the channel command, but I'm unsure if people ever want to use color.

We could also make it channel specific - allow tagging certain channels as allowing color codes, others not. I'm not sure if there'd be much use for that offhand, but might be worth doing just in case since it'd be fairly trivial to add a tag/attribute check.

**Comment by earthsend** [comment]
I'm not sure if this pertains to chat channels, but I do agree that it'd be an easier user experience if the `@setting` itself just computed the color argument after the command's syntax to be prefixed with { or |.

**Comment by TehomCD** [comment]
Escaping the code in `@setting` is something we could do too, sure. On an unrelated note, be sure to enclose anything that starts with an `@` inside backticks, or it's treated as tagging a user about the issue - I went ahead and edited your post to add that.
