### ISSUE TITLE
Favor/All Sorting

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#19]
**Is your feature request related to a problem? Please describe.**
Right now I'm not sure what favor/all is sorting by. At first it seemed to be sorted by creation date of the favor, but then some stuff started ending up at the top of the list instead of the end, or in the middle, and I don't know!

**Describe the solution you'd like**
Could it sort by creation date of the favor (presuming that data is saved) so it's easier to check for new ones? SOME OF US ARE NOSY AND WANT TO KNOW ALL THE BUSINESS DON'T JUDGE ME

**Comment by TehomCD** [comment]
The favor command is [here.](https://github.com/Arx-Game/arxcode/blob/stable_orphan/commands/base_commands/social.py#L3570) 

Right now, favor is an integer field in someone's [Reputation](https://github.com/Arx-Game/arxcode/blob/stable_orphan/world/dominion/models.py#L3288) model, which represents how an organization feels about them. Reputation doesn't have any ordering rules set, so it uses the default which is by ID, so essentially by creation order.

We could add a timestamp to when favor is applied by the command. That would then let us sort by the most recently modified.

**Comment by ApostateCD** [comment]
So I think that favor/disfavor should also expire automatically, probably on a one month timer, because otherwise we get these weird things of someone staying favored/disfavored forever long past whatever they did is relevant. I think we should probably make it more compelling for the social cost/more impactful on the lower end of orgs though.
