### ISSUE TITLE
Clue share failure cost

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#262]
Right now characters pay the AP cost of sharing a clue regardless if the clue share is successful or not. I think this leads to excessive OOC chatter regarding which clues people possess in order to avoid wasting AP.

This could be solved by adding an if statement here
https://github.com/Arx-Game/arxcode/blob/6c60b99a0843f4f27ad6dd102afa1bc55846d6bb/web/character/investigation.py#L1453
```
        counter=0
        for targ in targets:
            for discovery in discoveries_to_share:
                if not discovery.share(targ.roster, note=note):
                    counter+=1
                else:
                    shared_names.append(str(targ.roster))
         self.caller.pay_action_points(0-counter*self.caller.clue_cost)
```

**Comment by rozzingit** [comment]
This was actually on purpose, I know. Back when they added a cost to share clues, it wouldn’t let you share if the other character already had it. It was changed because it was an OOC indicator of IC lying with characters who had IC reason to pretend like they didn’t know about a topic or a piece of information. So it was changed in order to protect that aspect of IC interaction. 

Of course, I imagine it’s awkward to get asked OOC if you have a clue if your PC is trying to lie about it, too.

**Comment by Zironic** [comment]
That never changed. You still get the notification that the person you're trying to share with already has the clue.

**Comment by rozzingit** [comment]
No, if someone tries to share a clue with you that you already has, the game tells the _target_ that it was attempted. It doesn't tell the person giving the clue. I can confirm because I just sacrificed 2 AP sharing a clue to someone who already had it, RIP. It gave me the usual message about sharing the clue as if it were successful, and it told me target that I attempted it but they already knew it.

**Comment by Sritterbush** [comment]
I am in favor of this change because fooling players instead of characters leads to shitty people being encouraged to be shitty people.

**Comment by somethingfinite** [comment]
I'm against this proposal, as I think that it would put a lot of OOC burden on players playing deceptive characters. 

I do think that this is a problem, but I'm deeply skeptical of use cases where a character is truly sacrificing much by losing out on 2-5 AP. So, unless you're clue dumping on someone - which, you know, don't - this is hardly something that's more than, 'Oh. Lame.'

Alternately, why not just divorce sharing from AP entirely and treat it like teach? Instead of having your costs lowered, you can share 'x number of clues per week', depending on social stat?

That way the stakes are even lower, as at worst, you just lost clue shares, not AP, and it discourages mass info dumping.

**Comment by rozzingit** [comment]
Yeah, I have to agree with @somethingfinite on this. It also follows the rest of the overall game philosophy wherein IC knowledge and OOC knowledge are generally mirrored in the vast majority of cases. You don't have to chat OOC about this; it's very possible to ask IC questions and get IC responses about "have you already seen the journal by X that talks about Y."

ETA: I agree on not changing the code as it exists now, that is. I don't agree on divorcing clue sharing from AP.

**Comment by TehomCD** [comment]
Agreed. Won't change this for now.
