### ISSUE TITLE
Prune search results by visibility

### ISSUE THREAD

**Issue by TehomCD** [Arx-Game/arxcode#326]
Either using view lock directly or a new method, prune the list of objects passed from contents to search in the character search method based on whether the character can see them. Bypass for `is_staff`.

**Comment by Zironic** [comment]
The place to do that is here:
https://github.com/Arx-Game/arxcode/blob/26844da6586816430a9842127679e31ab06fc8f2/typeclasses/rooms.py#L475

You need to filter looking_at_obj by using looking_at_obj.access(caller, "view") before passing it to _AT_SEARCH_RESULT which is the error handler.

**Comment by TehomCD** [comment]
Thank you, but I think it's better to do that in the actual search method of characters so that it can apply to any command using search, rather than just 'look'. I believe the exploit the character most recently banned for was using 'lock', for example, and generating the multi-match that way. The look command from extended room has addition handling for 'details' that might be set in a room if it doesn't find an existing object, but the search method curates the objects it finds before it gets to that point.

**Comment by Zironic** [comment]
The multi-match itself happens here: 
https://github.com/evennia/evennia/blob/master/evennia/utils/utils.py#L1873

I think checking the view lock in there will be more complicated though because I don't know what other code calls the multi-match and what kind of weird things might happen if you naively check the view lock at that point.

In theory, just checking the view lock inside the for loop that's building the error message should work?

**Comment by TehomCD** [comment]
I think I probably wouldn't want to override the multi-match function since it's sort of weird and overloaded: it's also used for command mutli-matches, if I recall right, so you can't even rely on it being given typeclassed objects. For example, if you added a view check in there, every command in the game would instantly become invalid due to not having a view lockstring, I'm betting.

**Comment by Zironic** [comment]
Shouldn't you be able to use isInstance to ensure that you're only filtering exits and not any other typeclasss or  command instance?

**Comment by Zironic** [comment]
I believe this code should work assuming it doesn't cause an attribute error:
```
            from typeclasses.exits import Exit
            if not isinstance(result,Exit) or result.access(caller, "view")
```

That will only handle a multi-match however. Handling the case where there's only one possible target requires additional logic because blanket blocking it would make it impossible for anyone to use the invisible door. For instance 'look' is already coded to return 'Could not find X' if view access is denied however CmdLockObject is coded to send you over here https://github.com/Arx-Game/arxcode/blob/1a0219a9f4f2f442162a3455068adaab57d41d89/typeclasses/mixins.py#L1007 where it checks lock permission and if you don't have permission, it'll tell you "caller.msg("You do not have a key to %s." % self)"

It's a simple fix for the lockmixin. We simply add a view access check to that error message. The deeper problem is that revealing hidden things isn't limited to just lock. 

Because Evennia is built on a MUSH framework where Exits are just an object like any other. Any <verb> command can be used on the exit to reveal its name and I'm not entirely sure how many of those there are. The primary one I've found so far is 'Get' which when used on an exit gets you 'You cannot get climb down <down>.' even if the exit is hidden. The solution there would be the same as it is for lock, suppress the error message if there is no view access.
