### ISSUE TITLE
The Haggle Roll

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#38]
Honestly the code for the Haggle roll bugs me because it's so inconsistent with all the other rolls in the game. 

For almost all the other rolls that involve prestige or clout in some way, prestige or clout is used to generate a percentage modifier which is then applied to the original roll. This makes prestige and clout enchance a roll rather then supplant it. 

However in the case of Haggle, for most intents and purposes Prestige /is/ the roll. A character with 1/0 Charm/Haggling and 3 million prestige is actually better at Haggle then a character with 5/5 and 30k prestige. Aside from the aesthetical concern of the Arx version of Mila Jovovich being a way better merchant then the Arx version of Warren Buffet I think it's problematic because it means the vast majority of characters built to Haggle arn't any good at it because they just don't have enough prestige and it's really hard for a new character to get to that kind of level. Especially if that character goes for skills like Economics or Haggling because those skills won't build the clout they would need to climb that prestige ladder.

**Comment by katiebot5000** [comment]
As someone with a newer commoner with Haggling that's meant to be a merchant, I can verify that its difficult to really justify using the Haggling for anything beyond the occasional personal use.  The AP costs versus the returns are just not enough without having crazy high prestige to boost those rolls.  It becomes the age old 'I need X to get Y but I need to be able to do Y before I can get X' circle and its a vicious cycle for anyone that isn't already high prestige.  You need the Haggling to get good deals on the materials so you can make clothes (and either model or sell them to others to model) so you can get the prestige.  But without the prestige in places, you're spending more on trying to get a decent discount than what prestige bump you would get from the materials is going to be worth.  Even selling resources isn't really viable without the high prestige because I end up spending more AP in trying to get the good deal than if I'd just sold the AP and bought the resources outright or off the broker.  And at least some people want you to be able to handle bulk sales of upwards of a few thousand resources, which would be great, but I can't actually get a roll good enough to sell more than 300 resources at a time, at which point you run into the same vicious cycle of spending more AP than you're going to get return from the sale.

Edit:  Its actually more cost efficient for me to sell my AP and buy the super discounted goods on the broker than to use Haggle myself.  And I have a 4/5 pool to Haggle with.

**Comment by TehomCD** [comment]
Yeah, I think I lean towards removing prestige modifying the roll entirely and raise the impact of the skill to compensate.

**Comment by katiebot5000** [comment]
It really does seem, at least for now, like the most balancing solution to Haggling.  I'm sure if you guys wanted to, you could absolutely find an appropriate modifier to the roll and make it maybe less of an impact to the roll than prestige is currently, but that would be a solution of months and this seems a good patch in the meantime.
