### ISSUE TITLE
Legendaries and XP

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#42]
I think the way Legendaries interwork with the XP tax right now is a bit awkward. Because of the fact that the cost is set to 1000 in the cost function but it's treated like any other skill in the xp-tax function (ie, it counts as 60 or 120)  it creates a situation where it's it's thousands of XP cheaper to buy a legendary if you buy it as your very first skill, for instance after a respec.
 
Maybe it would be better if Legendaries are exempt from the tax all together but you're limited to only one?

**Comment by TehomCD** [comment]
Yeah, maybe so. A mitigating factor is that tax on other things are inflated by a legendary and I'm not sure that's negative either: someone who saves up for a legendary immediately is unlikely to have other things purchased, so that'll be something of a penalty.

I do want to redo xp/skills/stats completely at some point so I'd be tempted to not touch anything related to it until then, but this might not be too disruptive.

**Comment by rozzingit** [comment]
It's true that the XP tax doesn't seem to treat a skill at 6 as being 1000 xp worth of skills. So @Zironic is right that the tax actually can come out very differently if you buy it early vs buying it later. I think from practice it's not the case that people saving up for legendaries have _nothing_ else purchased -- my experience is that they generally start off buying some stuff, and then stop early on when the tax starts hitting them. (Or they've basically respecced into it and bought their legendary first.) But yeah, definitely however much time is spent saving up for the legendary skill does have a bit of a balancing effect.

**Comment by Zironic** [comment]
Yes, the code currently treats a combat legendary as 120xp and a non-combat legendary as 60xp for purposes of the XP tax.

**Comment by TehomCD** [comment]
I went ahead and changed legendaries to count fully for tax. I think that'll probably resolve things for now, though can revisit when the xp/skills/stats systems are changed.
