### ISSUE TITLE
Potential issue with the legendaries commit

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#44]
While as far as I can tell, there's no current code path that uses cost_at_rank in this way*, it seems written with the intention of being two way symmetrical however you only added the new cost at one side. So cost_at_rank(skill,5,6) and cost_at_rank(skill,6,5) will now return different results. 

*The refund code seems to call cost_at_rank(skill, current-1,current)

Speaking of asymetrical XP code, if get_skill_cost is ever called with a value greater then 1 or a value less then 0 it will generate the wrong values because it will be calling get_skill_cost_increase(caller) at the current rating. 

It also looks like the CmdAdjustSkill uses the original price paid for a skill to calculate the refund. The problem with that is that if a character refunds one of the first skills they ever bought, they'll get the base XP cost back. However due to the XP tax, that's no longer enough XP to buy that many dots in a skill.

Lastly a question, did you intend to double the cost of combat legendaries?

**Comment by Zironic** [comment]
I also think you raised the XP cost of buying your crafting ability 6 from 25 to 500.

**Comment by TehomCD** [comment]
Doubling cost with combat legendaries was something asked for ages ago that I never bothered to do. `cost_at_rank` is only used if the price wasn't stored in their skill history, which will not happen with legendaries unless they started with it during character creation or it was assigned to them manually, so it shouldn't be possible for it to return wrong values under normal usage. Refunding a skill will lower their tax proportionately to the skill's cost while restoring the xp used to buy it, so I don't really see a problem with that.

Crafting abilities aren't in the `VALID_SKILLS` tuple, they're in `CRAFTING_ABILITIES` and `VALID_ABILITIES`, so that should work normally unless I'm missing something.

**Comment by Zironic** [comment]
Yes, you're right. Crafting abilities should be fine.

However for the refund cost, unless I'm reading something very wrong will look like this.
Character buys combat ability 5 during chargen at 100% normal cost.
Character buys 100 points worth of stuff, their tax is now 200%
Character gets combat ability 5 refunded, gets 300 xp
Character now has a tax of 140% because 320 points is 60% tax
Character tries to buy some other combat ability 5, this would cost them 28+57,6+91,2+131,2+180 = 488

**Comment by TehomCD** [comment]
Let me try to run through this.

Character get a level 5 combat skill during chargen.

They buy 1000 xp worth of skills (which costs a bit more as the cost increments per buy, but w/e) and now have a tax of 200%.

They get a combat skill 5 refunded. If it was the one bought during chargen, it'd use `cost_at_rank` to determine the base cost of that before tax is 100+80+60+40+20, and return that to them. Otherwise it'd look at their `skill_history` attribute to determine what they paid, and refund that amount.

Their tax should now be the equivalent of having 700 xp spent, or +140% tax.

They try to buy some other combat skill 5, this would cost them:
20 * (1200/500) + 40 * (1220/500) + 60 * (1260/500) + 80 * (1320/500) + 100 * (1400/500)=788

I don't necessarily see this as a problem, though, unless I'm missing something here. Staff could refund other skills until their tax is entirely gone and let them repurchase whatever, and it should wind up at the same spot. You're right that if they refund a chargen skill, the xp values won't be equivalent to buying them now. However, chargen skills don't count towards tax, so early buys would be untaxed in the hypothetical "rebuy everything" route, effectively taking their place. Characters would probably come out ahead due to training, but eh.

**Comment by Zironic** [comment]
Yes, they'll be perfectly fine if they're refunded down to a blank sheet. However anything other then a blank sheet (or down to whatever their chargen stats were) will make them effectively lose XP unless the skill refunded is the last one they bought.

The way to fix this would be to instead of using the price they bought the skill at, just use the whatever teaching discount they had and do a normal skill train in reverse using the same XP cost averaging formula I proposed for the other issue. The problem ofcourse being that the teaching discount they used isn't stored in the database so there's no way you can do this for any currently existing skills accurately.

What you could do is refund them :
```
baserefund=(get_skill_cost_increase() * 2-cost_at_rank(skill,current-1,current) * 0.02)
if current < 5
min(max( baserefund * 0.55, stored_cost), baserefund) << Better of 45% teaching at current XP tax or stored
if current == 5
min(max( ( baserefund2 * 0.8, stored_cost), baserefund) << Assume 20% teaching for 5's
if current==6
max( baserefund) << Legendaries cant be taught so life is easy.
```

That should never give anyone much more XP then they spent while also not make them lose XP on refunds.

**Comment by TehomCD** [comment]
The only modifiers to cost are the teaching discount and the tax, so if you have the amount spent and the tax can be calculated, the teaching discount could be derived. It might be simpler to have refund always refund the skill + anything bought after it, though.

**Comment by Zironic** [comment]
That would be very easy but also potentially horrifying to the player who just wanted to move one or two dots around who find their character rolled back to a blank slate and might have to spend the next 3 months tracking down trainers.

Although if you did roll back a sheet that way, it would give you all the data you need to derive all their discounts and build it back up.

**Comment by emonical** [comment]
Should this be closed with a wontfix or invalid?

**Comment by TehomCD** [comment]
Sure. I don't think we'll revisit this unless I redo the entire skill/stat system.
