### ISSUE TITLE
Plots & Beats

### ISSUE THREAD

**Issue by thismynamenow69** [Arx-Game/arxcode#68]
**Is your feature request related to a problem?**
The restrictions on who can and cannot add a beat are frustrating, particularly when individuals who would otherwise be considered Mains on a plot have relevant information/actions/etc to add but are unable to do so. Making this go through the "Owner" of a plot adds an unnecessary burden to one person while also re-establishing the idea that plots can be claimed by one individual.

**Describe the solution you'd like**
Create the ability for players to go back and edit or delete beats. Make it possible for Mains to add beats.

**Describe alternatives you've considered**
Toggling people as GMs who are not GMs so that they can add relevant information to the plots.

**Additional context**

**Comment by TehomCD** [comment]
I could change it so that regular players could add beats/add to beats if it'd be helpful. My expectation would generally be that GMs would create them to add events that they ran, but it's a fair point about related action.

I'd want to double check to make sure that deleting beats won't cause cascade deletion for anything that points to it. It'd be kind of a bummer to have your actions erased that way, for example.

**Comment by thismynamenow69** [comment]
I actually did already request that a beat be deleted so I could redo it and the entire plot was deleted instead. Can confirm. Bummer.

**Comment by Nynrose** [comment]
This issue isn't specific to plot beats. Currently, people who are tagged as GMs of a plot, who are not plot owners, cannot create +prprevelations and +prpclues on a plot. For example, I have a +prprevelation ready to go, and when I used +prprevelation/create PLOTID=Story description, it did not link that plot to the revelation.  Without giving away plot detail, it shows:

Name: (Plot Name Redacted)
Desc:  (Plot Desc Redacted)
Plot: None  <------
Required Clue Value: 105

There's no other command with +prprevelation to link a plot to your revelation, and you cannot create a revelation without a plot ID, the system won't let you +prprevelation/finish without it.

**Comment by Precisi** [comment]
Not trying to tangent to another idea, but it seemed similar enough to the discussion at hand: As a player it would be nice to be able to add extra, editable OOC notes to a plot beat that is visible to all. This could help with multiple people managing a plot, possibly? Might want to limit the number of characters though to keep things from getting spammy in the timeline list.

Plot: Where did the bats go?!

Beat: One of the new theories that Magpie has is that bats actually went extinct from global warming. Mages in the past used way too many fossil fuels with their spells and greenhouses gasses heated up the etc etc etc... 
_OOC: Anyone that wants to follow up on this global warming idea, we have another subplot about it. Contact Magpie._ 

Then later a person might update that beat.. 
_OOC: Magpie was wrong, this has been disproved._

**Comment by TehomCD** [comment]
An ooc field for notes about a plot beat that's visible to players isn't a bad idea. PRPRevelations/Clues not being attached to plots sounds like a bug.

Edit: Fixed the bug about prprevelation and plots. In the future, please open bug reports in a separate issue for tracking, if you don't mind. It makes it easier to reference/close them with github's hooks for commit messages, since I didn't want to close this discussion.

**Comment by Tanookami** [comment]
The plots/editbeat switch should address the remaining issues here. Once a Plot GM vets an idea by creating a beat, anyone in the cast can edit that beat. Confirmation ensures nothing gets overwritten on accident, and the 'ooc' portion of the command appends to the ooc_notes field rather than replaces it. Wherever a beat's display method is called, those ooc notes should also display.
