### ISSUE TITLE
Combat Skills Rebalance

### ISSUE THREAD

**Issue by Sritterbush** [Arx-Game/arxcode#88]
**Is your feature request related to a problem? Please describe.**
Recently changes impacted the way characters reach the peak of performance in combat skills. This has caused me to take a step back to evaluate combat skills and think of alternative ways to handle them. 
-Combat skills cost twice as much as all non-combat skills.
-There are 9 combat skills, where social has 12 and intellectual pursuits have 15.
-One combat skill, survival, is a hybrid of endurance and outdoors skills. Resulting in many characters taking it for one of the two benefits when the second makes no sense.
-Small wpn, medium wpn, and huge wpn both influence not only offensive ability but defensive ability. A person cannot learn to defend against a weapon type without also learning to wield that weapon type. 
-Archery and Brawl, in contrast to the other weapon skills, do not aid in defense yet have the same cost.
-Skills are combat skills or not at present, there is no category for physical skills that extend beyond combat.
-Combat legendaries are similarly twice the cost of non-combat legendaries, but in practice cost more for a single combat legendary than two non-combat legendaries would due to how tax is applied.

**Describe the solution you'd like**
I would like to enable characters to more quickly and accurately realize their character's competencies, while also eliminating the two-tier cost system.
-Huge Wpn would be split into Huge Wpn Proficiency and Huge Wpn Defense
--Proficiency would be for attacking, defense would be for parry attempts
-Medium Wpn would be split into Medium Wpn Proficiency and Medium Wpn Defense
--As above
-Small Wpn would be split into Small Wpn Proficiency and Small Wpn Defense
--As above
-Dodge would be split into Dodge and Evasion
--Dodge would act as it did before against melee attacks, evasion would be a new archery/ranged attacks specific defense that acts in the place of dodge. There is still no parry for archery.
-Survival would be split into Survival and Resilience
--Survival would still cover outdoor skills, Resilience would replace survival for combat resilience mechanics
-Athletics would be split into Endurance and Athletics
--Endurance would cover fatigue and checks related to doing activities for a long period of time, Athletics would cover feats of strength and agility as it has previously
-Archery, Brawl, and Stealth would be unchanged
--These skills, for various reasons, have always been considered mechanically weaker than the other combat skills. This would still involve reducing these skills to the same base cost as non-combat skills, potentially resulting in a one-time xp refund for those who had them before the change.

After this is done, there would go from being 9 combat skills to being 13. The new version of the skill Athletics would no more be combat specific than Ride is, making it a non-combat skill. Similarly, the new version of survival would be closer to the current version of streetwise that is parallel to it.

Closing pitch
Pros: This opens up more flexibility for the addition of skills impacting combat later, eases the balancing process, is more intuitive to new players, and can be done without changing the core of the combat system. Characters who want a story that involves legendary combat prowess can more easily achieve that, with more diversity, and fuller recognition if they do so twice.

Cons: Implementing the change would impact the majority of characters in Arx. Characters with skills being split can be given both of the skills, whereas those with the skills being discounted would have to be refunded somehow. The change would require changing what skills certain combat mechanics call, if not the mechanics themselves. This may prompt a wave of characters asking to respec. Wpn Proficiency/Defense is sort of lame sounding, even if the skill split makes sense.

**Describe alternatives you've considered**
The staff has mentioned previously that combat as a system is something Tehom wishes to rework, but is a lower priority than other systems. A combat system redesign could notably alter what skills exist and how they're used, making my proposal either ineffective or irrelevant. However, that does not seem as though it will be happening soon.

**Additional context**
The goal in this proposal is to make it easier for people to enjoy the game, make the mechanics more intuitive, and help those characters who had the path to legendary status changed by the recent tax changes once again see that story goal as obtainable.

**Comment by Zironic** [comment]
What I think is that a major skill rebalance including adding a bunch of new skills is probably best paired with the same change that removes training xp and provides a good reason to provide everyone a full reset.

**Comment by TehomCD** [comment]
Yeah, I'd prefer large changes mostly be accompanied by the skill revamp where I move them into their own app and stop having hardcoded references, can store training time/xp spends in a better manner, etc.

From a perspective of player fun, I think it might be better to divide skills into further specialization/combat techniques with diminishing returns for higher tier skills might be better for player satisfaction. Being able to more narrowly define what a character is good at and creating some specific scenario where they'd be more effective against types of encounters probably feels better than "he can attac, but he cannot defen", if that makes sense. I wrote up a design doc for a proposed combat revamp at one point, I'll probably slap it up on projects when I get time for it for people to poke at. I would prefer skills/stats to be changed first, though.

**Comment by earthsend** [comment]
I do not think that increasing the gamut of skills will be good for game balance, or necessarily allow a character to benefit from a lower tax, since in effect he or she would be spending three times as much to raise a skill. I am also opposed to  a full reset without considering the impact on the code workload, as it would be significant.

What I would propose is to open abilities in the same way that crafters must specialize into different areas. I'll be working on something that's coherent and appropriate to that, but suffice to say that it would make use of custom combat emits and apply modifiers to defense or attack, depending on the style. For instance, if I were to write a 'sword and board' ability, it would do the following: each ability point decreases the difficulty to defend by 1, while also increasing the ability to parry and riposte. The tradeoff is that you'd have to use it with 'stances', and it would increase your difficulty to attack by the same ability points. Or perhaps it would give you a disadvantage on initiative. Conversely, the 'Florentine School' ability might drastically decrease your difficulty to attack, perhaps granting a more strategic application of attack/critical, while increases  your defense difficulty.

**Comment by rozzingit** [comment]
I find the idea of splitting a bunch of combat skills into two different sides to be highly _less_ intuitive, not more. It also seems strange to me to devalue Brawl when it's often used by abyssal monsters in live GMed combat situations (and those monsters will become way more accessible once shardhavens are live).

> What I would propose is to open abilities in the same way that crafters must specialize into different areas.

Yeah, that was pretty much the gist of the last combat revamp proposal I got to see from @TehomCD. A number of different fighting styles, and they all kind of had advantages and disadvantages vs other fighting styles. And I agree with him that stuff like that can provide a lot of satisfaction just because people really love digging in to what makes their character SPECIFIC and SPECIAL.

**Comment by hellfrogger** [comment]
I am very strongly opposed to changes that aim to optimize and reduce the cost of optimization without any balancing weakness or vulnerability built in. Choices made IC need to be meaningful, and we are trying to provide a game for rich roleplaying experiences for complex characters - characters with flaws, and weaknesses.  Any system has to have built in advantages and disadvantages, as the one Tehom has been dreaming of so lovingly.

**Comment by earthsend** [comment]
It expands the minigame's strategic considerations by a whole lot. A huge wpn user with 'staff fighting' could become a parry/riposte powerhouse almost as much as the sword and board guy, or maybe even _more_ but with less attack capabilities. If we're to take John Wick's (not to be confused with the Keanu Reeves character) design in fighting systems, it would look somewhat like this:

add combat.abilities or what have you to the character's list of stances

for every point in 'staff fighting' ->  decrease defense difficulty by 2 (and decrease parry difficulty by 1), increase attack difficulty by 3

upon parrying (which might need to be changed to player's native weapon skill while the difficulty to parry is increased by a further +5 or +10 to difficulty contrasted against the attacking player's roll), check riposte 

provide custom emit for the riposte if successful, increase static damage bonus to the end of the roll, also balanced to the rank in the ability.

**Comment by TehomCD** [comment]
I'm for expanding strategic choices for a party, in thinking what sort of combinations of different specializations would be optimal for a situation, trying to come up with plans of attack or how to work together. Having trainable styles with pros/cons that would be better/worse in different situations fit from this perspective, since it can provide people with a niche in which they might shine in specific situations. Tricky to make those situations seem equally valid and intuitive from a story perspective, but it doesn't need to be perfect as long as you can make people feel valued where they should be.

The danger comes from changes that increase complexity and provide benefits from mechanical knowledge that guide their decisions if those make little narrative sense. While theorycrafting is fun for the person doing it (at least if they enjoy that sort of thing), it comes with a cost of raising the barrier to entry to engage in a system and provides advantages to people that are completely divorced from any in-character decision. While it's a great move for a fighting game to provide rewards for investment in its core mechanics, it's a poor match for a game in which combat is meant to act solely in service to story and the interest of most people are just in how a scene players out, not the underlying mechanics of why it does so.

tldr - I'd want changes that play into a character's identity and provide them with moments of high drama where they get to shine, but we need to make sure combat doesn't get in the way of story.

**Comment by earthsend** [comment]
Given that there's no way to predict the outcome of a live combat situation, the system-in-service-of-story part is satisfied. 

The design of specializations based in styles that I suggest _has_ to come with some idea that you choose what makes the most sense for your character. At some point, there has to be some room for flexibility for players to make the best stylistic choices for their characters, but also significant drawbacks that the choice has to be weighed against what's reasonable for them to learn. A +18 difficulty debuff to offense, in my above example, for someone with 'staff fighting' at 6, gives the character an opportunity to shine in, say, protecting a village against a gang of criminals. Not so much in killing Monster McWeeklyFlavor, where the odds are already stacked against her to begin with.

As a note, there are three 'swordsman schools' in 7th Sea that I'd like to point out as being good examples of this: El Punal Oculto, Villanova and Larsen. With mechanical strengths offset by situational drawbacks, the choice in investing in these styles makes for risky and _fun_ situations.

**Comment by TehomCD** [comment]
Right, my point is that the situations of producing a satisfying story event from a given style need to be clear and well-defined to justify the cost of additional complexity before I think it's worth it for it to be added. I really don't think a nebulous "eh maybe this will come up here" is sufficient - I'd want a pretty clear story written of exactly when it would compared to alternatives. If there'd be overlap with something else, that's not good unless it'd provide a clearly distinct flavor.

The bar they'd have to hurdle before an addition is justified needs to be at least a little steep because asking people to understand more about a mechanical system is not a trivial cost to impose.

**Comment by earthsend** [comment]
Would documentation help with this? It's possible this could be further customized by giving players the opportunity to make their own maneuver-success emits or something of the sort.

**Comment by hellfrogger** [comment]
Hmm, think more along the lines of specific narrative tropes or niches one skillset could fill that would make them attractive to a party while also opening up a different trope/niche they would be weaker at that another spec could fill.  I think it's less about 'what would feel cool to the person doing it" and more "what creates worthwhile narrative depth/what creates a specialization that would be wanted"

**Comment by earthsend** [comment]
Do you think this would be best accomplished by separating the styles according to what's more thematic in each fealty without actually limiting a character's given choices in personal flair to their regional allegiances? I see the merit in your argument based on how some people opt to play swashbucklers vs heavily armored knights and so on.  I'll try to write a few examples within five different archetypal matrixes: pirate/sailor, knight, barbarian/shav, duelist and soldier.

**Comment by Zironic** [comment]
If you view combat from a very abstract view of 'What would players want to specialize their combat character in?' I think these would all be very popular.
1) Keeping your friends alive in a Shardhaven.
2) Being the best duelist/champion ever
3) Being the best monster slayer ever

**Comment by earthsend** [comment]
I am more thinking in terms of being able to do all three, depending on the _situation_, but specializing towards a motif/flavor. The guy that's all offense, all the time, might not be able to sustain hits from a Gigantosaurus but fighting defensively has its drawbacks: namely, you still need to be able to hurt Gigantosaurus.

**Comment by ApostateCD** [comment]
As a general rule, I'd want people to keep in mind during suggestions, is I'd never want any options that are counterintuitive where a brand new player picking up a combat character could make choices that result in them losing a fight against an experienced player playing a less capable combat character, on average. Anything that would result in that outcome I'd block, as I don't want familiarity with combat mechanics to be a factor for success. So the implementations have to be very simple and intuitive that always make sense for characters.

**Comment by earthsend** [comment]
That's why the spirit of my suggestions are to have synergy with the existing framework for combat: so that you don't choose X over Y because it'll win you the most fights, but because it's what makes the most sense for your character. The unpredictable nature of dice letting outcomes dictate themselves. And also why working them into stances is probably the best way to conform to simplicity in design. Adding new functions as new combat goals would turn it into a lot more involved and counterintuitive process.

**Comment by Sritterbush** [comment]
I agree with Apostate's viewpoint, the system should be intuitive. The current system (where parries are tied to the combat skill being used against you) has been cited as a cause for confusion by people since that change was made. While I agree that more skills add complexity, I do feel people seeing a 'defense' skill does highlight that defense is not, as the system is currently built, tied to proficiency with the weapon you are using. Which is in itself counter-intuitive for many.

I am very excited for the eventual specialized combat system that Tehom has in the works. My goal here was something smaller and easier to implement in the current design timeline, where the combat overhaul may be far off still.

In response to the comment on brawl being a poor skill to discount, I had forgotten that the inability of brawl to 'parry' wasn't the same as brawl being unparryable, as it is with archery. I would gladly alter my proposal for brawl to be split as the wpn skills are. 

Also in answer to earthsend, this comes with the goal of changing combat skills to have the same base cost as non-combat skills, so it should not result in three times the cost. With tax effects factored in the costs are comparable for picking up two skills at the non-combat rate to one at the combat rate.

**Comment by Sritterbush** [comment]
In answer to the reference to 7th Sea, I want to point out the Exploit Weakness feature in 7th Sea because it might be another way to look at these design possibilities. For those unfamiliar, you would have Exploit Weakness (Style) and when fighting someone who uses that style, gain certain advantages. This is similar to the way having proficiency in a weapon now gives parry advantages in Arx, though more complicated since everything in 7th Sea is pretty theory heavy.

**Comment by LadyNyxx** [comment]
There are a lot of interesting ideas here.  

I've always thought brawl should modify any melee or defense skill.  A kind of a booster that can give a fighter an extra edge that can aid in an up close and personal dust up.  I'm not sure brawl would aid in a distance weapon skills such as Archery, however, as that requires a different sort of skill set and brawling doesn't seem to fit that.   

Out of curiosity, which skills are currently used for thrown weapon skills (aka. knives), if any, and is there an appetite to add a skill for dual melee weapons?  Nothing to imbalance. Perhaps it can offer an improved chance to hit a target and/or do extra damage?

**Comment by Sritterbush** [comment]
Nice to see a new voice in these conversations.

I had proposed at one point an option to slip a brawling attack (attack/unarmed) into a fight using weapons as a sort of surprise attack. attack/toss or similar might also be good, though I wonder how we'd manage thrown weapons. Will it be like arrows, where they're sort of handwaved? I would be hesitant to make brawl a flat passive boost that is always in effect. As to dual weapons, I expect they'll be looked at when shields are likewise figured out. Hard to imagine what that will be like mechanically for me.

**Comment by LadyNyxx** [comment]
I suppose I'm looking for a way to creatively (and justifiably) use brawl in fighting.  Right now it's kind of an underused skill.  I have rarely seen it used with any effect.  Everyone is pretty march armed too the teeth all the time. Which kind of makes me question, why bother having brawl at all if no one really uses it. I can see why, though. It cannot compete with any armed forms of combat as far as I've seen nor can it be used to bring any benefit to a knock down drag out fight.

**Comment by earthsend** [comment]
I disagree, regarding brawl modifying melee or defense skills. This might lead to further complexity in combat than intended. If it's supposed to be intuitive and straightforward, anyways.

What I do suggest for keeping things simple and also allow new players and experienced players to engage in combat on even grounds is to write a Combat Guidelines news file. At least explaining that the default difficulty to attack and defend is 15, the role of dodge and the opponent's weaponskill in defense rolls, what attack/critical is good for, et cetera.

At present, you need to read about 4 helpfiles to even start to grasp the combat system, and it's really hard to explain to someone else what Soak Rating and Mitigation does.

**Comment by Sritterbush** [comment]
I think a 'help combat' with guidelines on mechanics is a sound suggestion. I recognize that staff has previously said they don't want people to focus on mechanics over story, but with such a crunchy system where misunderstanding mechanics can be quite fatal, there is a solid case for informing players.

**Comment by LadyNyxx** [comment]
I think being able to understand just what your character can do helps guide the RP, though.  

I mean, I look at one of my alt's stats and I think, okay, she should be pretty tough.  She's pretty much useless and has never won a fight. Now, granted, a lot of that could be my fault as a player who's learning the fighting ropes. But it would be stupid for me to RP a badass who has no firepower to back it up.  And even more stupid to go swaggering into a dangerous situation without knowing just how capable she is or is not.  

A guide that can show you how to navigate that and figure where you stand might be helpful. At least for a someone newer to all this like me.  :)

**Comment by hellfrogger** [comment]
Brawl is a skill for brawling. It's not for war or soldierly training. If you get into a fight with a character at a bar, they can't draw a sword on you - weapons are peacebonded in public, and it would get them arrested. But fistfights can and do happen.

**Comment by Sritterbush** [comment]
I'm fine with that reasoning, but then the mechanics should reflect that reality. It makes little sense for Brawl to be treated as a non-martial, non-soldierly skill while also treating it as the primary defense skill against threats in staff run events or shardhavens. It has been suggested that may be the case above. That feels like two different visions.

**Comment by Zironic** [comment]
I think if you want it more intuitive, you can give monsters a new attack skill (not brawl) and allow PCs to buy a new skill that's dedicated to monster fighting. That would leave Brawl extremely niche however.

Either way, I do like the idea of splitting survival/resilience and athletics/endurance paired with making athletics, endurance and survival non-combat skills because it'll make it a lot easier to make athletic/outdoorsy characters that arn't primary combatants.

**Comment by earthsend** [comment]
I don't really see a merit in splitting athletics and survival just for the sake of making an 'athletic/outdoorsy' character. Athleticism and knowing how to forage, follow tracks and create a lean-to in the middle of a forest are skills with martial worth, and it makes sense they'd be weighed as a combat skill for that, along with their benefits in fatigue, mitigation and shock.

**Comment by Sritterbush** [comment]
Yet streetwise, ride, and war are all arguably just as valuable in combat situations. Yet none are charged at the combat rate, in part because they're support skills rather than the actively applied ones in combat itself. At least by my read of things.

**Comment by earthsend** [comment]
Ride's war applications are very strictu sensu, there's no real application to streetwise in a do or die situation other than 'I know which alleyway leads to Main Street with Fifth' and war is about the scholarly study of strategy. You can be a great strategist without having ever set foot in a battlefield, after all.

**Comment by IanFromArx** [comment]
From the perspective of someone who's used coded combat for spars with some really rich, exciting description, I don't think the system needs many more bells and whistles than it has.   At the end of the day, the dice go how they go, and you describe it how you describe it.  I've managed to create a build with a unique combat style (the thing Ian does where he doesn't. go. down and then comes back at the end out of nowhere with some finishing move that probably shouldn't be allowed in a fight between gentlemen like the infamous basket hilt to the face) and I've done it entirely with what I've chosen to buy, statwise, and my use of stances, attack/critical, and attack/accuracy.

Do ALL fights end with basket hilts to the face?  No.  Sometimes Ian is overmatched, and he loses.  That's the whole point of having stats and dice -- to create an environment where your character isn't perfect and will sometimes lose.  When that happens, I describe him as being overmatched and losing, and that can make for good story, too.  

I'm terrible with numbers, math, and statistics and at the end of the day I really just want to play my character and have him do cool stuff.   So the expertise I used to create a combat style for Ian was mostly trial and error during IC spars.  I've also gotten help, especially in the beginning, from more experienced players.  For example, during the stretch of time Harald was teaching Ian to fight, Harald's player was teaching me about basics of mitigation, fatigue, etc.    (The basket hilt punch move also came from Harald's player.)  I try to pay it forward by doing the same when I think it's something the person wants to learn about.

Having a system just complicated enough that it requires time spent sparring to really master makes sense from an in character perspective. If you don't practice, you start to lose your edge.  A spar is just playing out the act of practice, encouraging such things to be done on screen.

As for someone new to the game coming in with a character who's supposed to be a badass without stats or OOC experience to back that up, my suggestion would be to work under the assumption that anyone recently arrived in Arx is a little rusty for whatever reason.   Maybe they were injured recently and have been recovering.  Maybe they just haven't done a lot of fighting lately.   Maybe they're used to one very specific fighting style and running up against people who fight in so many different ways is taking some getting used to.   Maybe they're a super badass who's not used to pulling their blows in a fight like all these "civilized" people and it's throwing them.  With practice roleplayed out in the sparring ring, they'll both earn XP to spend on combat stats, and a better OOC understanding of how the system works, and their character will get better.

We as roleplayers I think sometimes try to lean on mechanics to do things that we should be doing with described SFX.   And sometimes that's fun.  It's why games like Pathfinder exist in all their fiddly glory, and I love Pathfinder.  But it's not necessary, and it's not particularly newbie friendly to do things that way.  From the perspective of someone who's used a great deal of the combat system, both in lethal and non-lethal circumstances over something like a year and a half now, I think that about the right balance has been struck in this game between the two.  I've even come to see the value in the new parry rules, after I got over the initial 'oh crap I'm going to have to buy so many more things my XP tax is terrifying'.

What I WOULD say is that it might be a good idea to:  

1) Create a special rostered character background that only shows up while they're on the roster, something to give a new player a more realistic sense of the character they're playing and why said character isn't going to just come in like a wrecking ball (probably).  

2) Encourage new players to take advantage of the sparring areas and the Sip n Spar, which is both a great place to meet people and also a good place for someone who doesn't really know anyone to find someone to fight with them.

3) Encourage more established players to be willing to OOCly show someone the ropes.   I don't think code needs to be put in place to reward people or anything as @randomscenes and voting do just fine on that front, maybe just a change in the language to the guidance for randomscenes to include someone who was helpful as an OOC mentor in the course of the scene.  This could apply to learning a lot of other systems, as well.

4) A fight/nonlethal command that would allow for a non-lethal spar in places that haven't been coded for them, so that people who wanted to RP said scenes in less public areas would have that opportunity.  I know not everyone likes the potential of their scene getting mobbed.  

5) A good, hard second look at whether combat styles are really going to add anything to the game that can't be gotten through less rule focused means, and whether what they add is worth the additional complexity they'd introduce.

**Comment by earthsend** [comment]
Combat styles, when done right, add flavor to a character's individual expression on a setting. If you can simplify their mechanics, you don't need to worry about their complexity. So long as the benefit is automatic once set, either as a stance or as a goal, it should become intuitive within even  a couple of spars.  I think 1 to 4 happens often enough;  setting a room as non-lethal combat is easy enough to do, after all.

**Comment by Sritterbush** [comment]
I would like to hear thoughts on one specific in this proposal that seems to have been less focused on, trying to bring combat skills in line with non-combat skills for xp cost instead of having combat at double cost per rank.

**Comment by hellfrogger** [comment]
It was done for a reason, and that reason still exists, so this doesn't seem likely anytime soon.

**Comment by Sritterbush** [comment]
What was the reason?

**Comment by ApostateCD** [comment]
Character loss. The economic incentives behind social skills are just insufficient to change it. If we made automated social combat that could (and did) result in non-con character loss for someone losing a social combat, we'd definitely even it out. I'm not saying we'll never do that either- I have considered it, though it's difficult to do that in a satisfying way.

But keep in mind that implementations of that to be 'even' with physical combat are probably harsher than people would think. This would basically have to be non-discretionary to staff almost, in a, 'well sorry you rolled badly, your character is gone'. Staff don't want to take away characters. If we make forgiveness an option, they basically always will. So it would have to be enforced on bad rolls. A combat beast that rolls badly in social combat would have to be dead, no question.

**Comment by earthsend** [comment]
To clarify: character loss due to player versus player combat in some way? Or character loss due to player vs environment situations?

**Comment by ApostateCD** [comment]
Both/either. As in that during GM events there would be automated social combat,and if a character lost that, they'd die. It would be exactly equivalent to automated physical combat. Not a, 'Someone said something dumb to a Big Bad and got squished', but, 'they got jumped by a social combat they didn't expect, lost, and are dead'.

**Comment by Zironic** [comment]
The problem Brawl has right now is that between Hairpins and Attack/Accuracy, it's just plain terrible in terms of lethal peacebond combat.
 
Brawl can't parry, it has 0 damage dice, 0 damage bonus and 0 difficulty mod.
Meanwhile something modest like an excellent Rubicund Hairpin can parry, has 5 damage dice, 8 damage bonus and -2 difficulty mod
 
Attack/accuracy currently allows you to trade damage for accuracy at a 1:1 ratio. This means that someone with 0 dots in Small Weapons fighting someone with 5 dots in Brawl can use Attack/Accuracy = 30 to trade 5 dice worth of damage for accuracy and still deal more damage then the brawler at the same accuracy while your defense is going to be better because of the parry.

The simple fix would probably be to give Hairpins to brawl, to make Brawl into the catch-all for peacebond. Either that or make brawl non-combat because it's not an appropriate skill to use for lethal combat. The complicated fix would be a complete rework of how weapons, damage and armor works that gives brawl a real place.

**Comment by TehomCD** [comment]
I think I'd be inclined to add brawling weapons, like brass knuckles, cestii, that sort of thing: anything worn rather than held, and then do various levels of reach contrasted with additional mobility modifying dodge.
